export const dogBreeds = [
  "Labrador Retriever",
  "German Shepherd",
  "Golden Retriever",
  "French Bulldog",
  "Bulldog",
  "Beagle",
  "Poodle",
  "Rottweiler",
  "Yorkshire Terrier",
  "Dachshund",
  "Siberian Husky",
  "Great Dane",
  "Doberman Pinscher",
  "Australian Shepherd",
  "Cavalier King Charles Spaniel",
  "Shih Tzu",
  "Boston Terrier",
  "Pomeranian",
  "Havanese",
  "Maltese",
  "Border Collie",
  "Basset Hound",
  "Mastiff",
  "Chihuahua",
  "Cocker Spaniel",
  "Boxer",
  "English Springer Spaniel",
  "Pug",
  "Shetland Sheepdog",
  "Weimaraner",
  "Bernese Mountain Dog",
  "Vizsla",
  "Collie",
  "West Highland White Terrier",
  "Brittany",
  "Rhodesian Ridgeback",
  "Newfoundland",
  "Miniature Schnauzer",
  "Papillon",
  "Bichon Frise",
  "English Setter",
  "Bloodhound",
  "Irish Setter",
  "Akita",
  "Belgian Malinois",
  "Alaskan Malamute",
  "Samoyed",
  "Pointer",
  "Whippet",
  "Shiba Inu",
  "Basset Hound",
  "Other"
];

export const catBreeds = [
  "Persian",
  "Maine Coon",
  "British Shorthair",
  "Ragdoll",
  "Bengal",
  "Abyssinian",
  "American Shorthair",
  "Siamese",
  "Scottish Fold",
  "Sphynx",
  "Russian Blue",
  "Norwegian Forest Cat",
  "Oriental",
  "Exotic Shorthair",
  "Turkish Angora",
  "Birman",
  "Himalayan",
  "Devon Rex",
  "Cornish Rex",
  "American Curl",
  "Burmese",
  "Tonkinese",
  "Chartreux",
  "Somali",
  "Manx",
  "Egyptian Mau",
  "Japanese Bobtail",
  "Turkish Van",
  "Selkirk Rex",
  "Bombay",
  "LaPerm",
  "Munchkin",
  "Savannah",
  "Ocicat",
  "Singapura",
  "Peterbald",
  "Lykoi",
  "Other"
];

